# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Disentangled Representation Learning
email: eliasageby@hotmail.com
description: This is a summary of the work presented in 'Introducing Sparsity into the Current Landscape of Disentangled Representation Learning'. I also provide a web-enabled demo of the results.

github_username:  eageby
# Build settings
markdown: kramdown
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme 

domain: eageby.github.io       # if you want to force HTTPS, specify the domain without the http at the start, e.g. example.com
url: https://eageby.github.io  # the base hostname and protocol for your site, e.g. http://example.com
baseurl: /disentangled-representations/      # place folder name if the site is served in a subfolder

titles_from_headings:
  enabled:     false
  strip_title: false
  collections: false
  
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
